### ISSUE TITLE
variantsToVRanges loses sample/call information

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/GoogleGenomics#52]
VRanges can manage all the information on samples and calls, but the
current function just acquires one record per variant.  Is this function/package
still in development?

**Comment by ttriche** [comment]
*(waits to see what the answer is, ponders patching this since VRanges has
turned out to be very handy for capture sequencing results and clonality
modeling)*

--t

**Comment by vjcitn** [comment]
Thanks Tim -- Let's be in touch before writing any code as there are some issues to think about regarding when to acquire the detailed data -- working directly with the JSON response or elaborating the current getVariants code ...

**Comment by siddharthab** [comment]
Hello Vince,

Thank you for your query. This package has not been updated in a while, mostly due to personal time considerations on my part, but we do intend to keep supporting it.

If you have a patch you would like me to review, I will be very grateful. Please read https://github.com/Bioconductor/GoogleGenomics/blob/master/CONTRIBUTING.rst before you start working on the patch.

Else, I will be happy to work on your suggestion in my next set of updates.

**Comment by siddharthab** [comment]
This has been fixed by contributions from Vincent Carey and his team in pull requests #54 and #55. The changes are also available in the bioc-devel repository.
